<div class="card-columns">
    <div class="card my-3">
        <img src="/static/doesntWork.jpg" class="card-img-top">

        <div class="m-2">
            <span>It isn't working now :(</span><br />
            <i>#sry</i>
        </div>

        <div class="card-footer text-muted">
            <div class="row">
                <div class="col">
                    server-tyan
                </div>
            </div>
        </div>
    </div>
</div>
